import urllib.request
r = urllib.request.urlopen('http://localhost:5000')
content = r.read().decode('utf-8')
print("magic-effects.css present:", 'magic-effects.css' in content)
print("magic-bg-glow present:", 'magic-bg-glow' in content)
print("pulsating-btn present:", 'pulsating-btn' in content)
print("MagicUI Effects present:", 'MagicUI Effects' in content)
print("login-magic-wrap present:", 'login-magic-wrap' in content)
print("magic-entrance present:", 'magic-entrance' in content)
print("trackMouse present:", 'trackMouse' in content)
